default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: quiz2_development

test:
  <<: *default
  database: quiz2_test

production:
  <<: *default
  database: quiz2_production
  ## username: quiz2
  ## password: <%= ENV['QUIZ2_DATABASE_PASSWORD'] %>
